### ISSUE TITLE
API documentation is listed in reverse alphabetical order

### ISSUE THREAD

**Issue by premasagar** [fitzgen/wu.js#26]
Great library.
Presumably a bug(?) - the docs site's API methods are listed Z to A: http://fitzgen.github.io/wu.js/#API

I think a link to the GitHub repo near the top of the docs page could be a useful addition too.

**Comment by fitzgen** [comment]
This is (sort of) an issue with Jekyll. Every method documented has its own post in `_posts/` and every post is dated `1-1-1` because that was easiest at the time (and I didn't and don't want to sort manually via post dates). For whatever reason, Jekyll puts them in reverse order.

I really do not want to order them myself by changing the post dates, as that would make adding/removing methods and keeping the sorted order correct involve a lot of manual work.

Perhaps there is an option somewhere to make Jekyll do this for us automatically?

**Comment by rajington** [comment]
Forgot to check if there was already an issue open, submitted a PR here: https://github.com/fitzgen/wu.js/pull/38

To sort you need to "assign" it to another variable, but adding "reversed" also works

**Comment by fitzgen** [comment]
Fixed in #38
